platform :ios do
    desc "Load ASC API Key information to use in subsequent lanes"
    lane :load_asc_api_key do
      app_store_connect_api_key(
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_KEY"],
        is_key_content_base64: true,
        in_house: false # detecting this via ASC private key not currently supported
      )
    end
end