platform :ios do
    desc "Sync Signing"
    lane :signing do
      # Add your signing tasks here
    end
  
    desc "Build Binary"
    lane :build do
        signing
    end
  
    desc "Release"
    lane :release do
        build
    end
  end
  