name: Build And Deploy iOS App To App Store
on:
  push:
    branches: ios-cicd-sj
jobs:
  build_and_deploy_ios_app_to_app_store:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Decode signing certificate into a file
        env:
            CERTIFICATE_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }}
        run: |
            echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12

      - name: Build & deploy iOS release
        run: bundle exec fastlane build_upload_testflight
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.P12_PASSWORD }}
          SIGNING_KEY_FILE_PATH: signing-cert.p12
      